spring.application.name=gulimall-cart

gulimall.thread.core-size=20
gulimall.thread.max-size=200
gulimall.thread.keep-alive-time=10

server.port=40000
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.redis.host=169.254.139.10

spring.main.allow-circular-references=true